In [1]:
import os
import glob
import pandas as pd
import xml.etree.ElementTree as ET

In [4]:
def xml_to_csv(path):
    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        root = tree.getroot()
        for member in root.findall('object'):
            value = (root.find('filename').text,
                     int(root.find('size')[0].text),
                     int(root.find('size')[1].text),
                     member[0].text,
                     int(member[5][0].text),
                     int(member[5][1].text),
                     int(member[5][2].text),
                     int(member[5][3].text)
                     )
            xml_list.append(value)
    column_name = ['filename', 'width', 'height', 'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df

In [6]:
#def main():
image_path = os.path.join(os.getcwd(), 'E:\images')
xml_df = xml_to_csv(image_path)
xml_df.to_csv('train_label.csv', index=None)
print('Successfully converted xml to csv.')

Successfully converted xml to csv.

In [13]:
os.curdir

'.'

In [8]:
xml_df

,filename,width,height,class,xmin,ymin,xmax,ymax
0,BikesHelmets0.png,400,267,With Helmet,29,105,82,160
1,BikesHelmets0.png,400,267,With Helmet,122,66,193,154
2,BikesHelmets0.png,400,267,With Helmet,201,43,246,98
3,BikesHelmets0.png,400,267,With Helmet,307,17,371,107
4,BikesHelmets1.png,400,300,With Helmet,161,0,252,82
...,...,...,...,...,...,...,...,...
1446,BikesHelmets98.png,400,231,Without Helmet,116,50,146,85
1447,BikesHelmets99.png,400,245,With Helmet,268,59,295,86
1448,BikesHelmets99.png,400,245,Without Helmet,161,52,193,83
1449,BikesHelmets99.png,400,245,Without Helmet,63,57,90,86
1450,BikesHelmets99.png,400,245,With Helmet,325,68,353,102